### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by aaramirezd** [uml-robotics/ROS.NET_Unity#1]
Hi Eric McCann.

Excellent work, thanks for the development of this tool.

Is it possible to update the guide to use ROS.NET_Unity?

I got used ros.net  with listener and talker solutions, running the ros master in ubuntu, but I have not been able to integrate this into Unity.

Thanks,
Andrés

**Comment by DCurtin** [comment]
I can look into this after finals, could you email me what particular issue
you're having with ros.net and unity?

**Comment by aaramirezd** [comment]
Hi, @DCurtin 

I am not clear what solutions (folders) i have to include in my unity project folder (<Unity project dir>/Assets/Plugins).

I do not understand the buildUnityScriptSource.bat  function, because i run the file but It seems to do nothing.

Thanks,
Andrés

**Comment by DCurtin** [comment]
The buildUnityScriptSource.bat should build necessary ros.net components and dump them in a COPY_TO_UNITY_PROJECT folder in the same directory. These files are what you want to drop in your Assets/Plugins folder of your project although it's suggested you do something to the effect of a symlink to make using git with unity slightly more manageable. 

You may also want to copy the Assets folder to your project, not into plugins but overwrite assets, it should only add the contents of scripts into the scripts folder of your project. The contents are mainly related to a sort of unity/rviz knock-off so it may not be applicable to what you're working on. 

If  buildUnityScriptSource.bat is giving you issues you may want to try and older version from before mesh copying was added? 
https://raw.githubusercontent.com/uml-robotics/ROS.NET_Unity/a0d3f25df02808ea6177aab3a1fc80ba9c91557c/buildUnityScriptSource.bat

**Comment by allspawj** [comment]
There are instructions for installing the core .net features on this repository README, and I have split off some tutorials in a separate repo for creating publishers/subscribers and plan to add some more tutorials there soon.

Please see https://github.com/uml-robotics/ROS.NET_Unity_Assets
