### ISSUE TITLE
Can't launch the demo 

### ISSUE THREAD

**Issue by HachemLamti** [uml-robotics/ROS.NET_Unity#2]
Hi Eric 

Nice work. 

I tried to follow your instructions in order to communicate with a remote ROS machine on Ubuntu and it works. I can publish topics and check them on the master machine. However, I couldn't display any data because it seems that the robot isn't sending anything. 

I wanted to know what am I supposed to get in Unity side ??? is it a robot ? a  map ? a camera ? because right now the only thing I get when I play the scene is the tri-axes. I don't understand if I did something wrong. 

Besides, your blog www.word.emccann.net/2016/03/ros-netunity-helloworld/ is unreachable 

Thanks

**Comment by allspawj** [comment]
If you are able to publish but not subscribe from ROS.NET the first thing I would check is your windows firewall. It must be disabled to receive messages. Also make sure that you are setting your ROS_HOSTNAME to something the other computer can resolve.

**Comment by HachemLamti** [comment]
Hi Jordan 
Thank you for your Email. I deactivated my firewall but it seems that the same issue persists. I think that my robot is not sending anything. 

Attached you can find a screenshot of my Unity scene. Please le me know if you need other resources. 

Bests
![rosissues](https://cloud.githubusercontent.com/assets/25687881/22828721/27c77704-ef9f-11e6-8639-4d59f461ee33.png)

**Comment by allspawj** [comment]
Sorry took so long to respond to this.

Do you have something publishing a robot state outside of Unity? I believe this sample only subscribes to the transforms of an existing robot, it doesn't simulate one on it's own. You will need to startup a stage or gazebo sim if you want to visualize something meaningful.

**Comment by HachemLamti** [comment]
Hi Jordan 

Wonderfull !!!! I tried to launch a gazebo on uwsim environment and I was able to vizualize the same model on Unity (although the orientation is inversed). 

My question is : is it possible to use this wonderful plugin  to publish topics from my Unity simulated scene to the remote server or should I code it from scratch ? 

Thank you very much for your help it works perfectly

**Comment by allspawj** [comment]
Absolutely.
It looks like there isn't an example of publishing a message here so I will probably add something.

If you look at one of the subscribers (like https://github.com/uml-robotics/ROS.NET_Unity/blob/master/Assets/Scripts/CompressedImageDisplay.cs)
you can see an example of how to setup a node. Just create a publisher, a message and publish it.
If you are familiar with the ROS c++ or python syntax it should be very intuitive.
