### ISSUE TITLE
Problems running demo 'TF_UNITY_TEST'

### ISSUE THREAD

**Issue by lee4138** [uml-robotics/ROS.NET_Unity#4]
Hi all,

thanks for this repo and the nice work! I have a problem running the demo and hope for your help :

I set up my project like the readme states (copied to generated files from the COPY_TO_UNITY folder into my projects plugin folder and also copied the Assets folder containing the demo into my Project). Now if I open the scene TF_UNITY_TEST it shows 5 Missing Prefabs in the Hierachy. And there are also some assembly reference errors like

`tf.net.emTransform' does not contain a definition for `UnityPosition' and no extension method `UnityPosition' of type `tf.net.emTransform' could be found. Are you missing an assembly reference?`

I got rid of some errors by installing some assets or uncommenting some code. But I am still not sure how to run use the demo.

Could you please help me with getting the demo to run,  so which steps are required and if I got rid of all errors just press the play button or do I have to build to a VS project and start there? and what should I see if the demo is working? The readme states that there is a visualization of the rviz map so I have to run RViz from ROS first and publish smt? 

Hope for  your answer and thanks very much in advance !

**Comment by allspawj** [comment]
Sorry I never got to this before. Are you still having an issue? 

The prefabs for the tf stuff seem to be broken, i'll take a look at them.

I have created a seperate repository, https://github.com/uml-robotics/ROS.NET_Unity_Assets

If you clone that repository into your Unity workspace, there should be a sample scene for publishing/subscribing. I'll add a scene with fixed prefabs for a tf visualizer.

**Comment by lee4138** [comment]
thank you very much for your reply! I wasnt using this project since then but will definitely have a look later on.
