### ISSUE TITLE
What version of Unity3D?

### ISSUE THREAD

**Issue by DanielArnett** [uml-robotics/ROS.NET_Unity#7]
Hello what version of Unity should I be using? I was using this successfully last year, but now when I revisit the project I'm getting bugs in Unity. What version of Unity (and what commit) do you use?

**Comment by allspawj** [comment]
I have had success with many versions of Unity, including several of the recent releases, the version shouldn't matter.

If you update the project from an old to new unity verison, you will probably need to create a new project in the newer unity version, then reimport everything for it to be happy. You also may need to update/reinstall the visual studio that comes with unity.

If those don't work, I'll need more info on what error you are getting to offer more help.
